name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby_version }} Rails ${{ matrix.rails_version }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby 3.2
          - ruby_version: "3.2"
            rails_version: "7.0"
          - ruby_version: "3.2"
            rails_version: "7.1"
          - ruby_version: "3.2"
            rails_version: "7.2"

          # Ruby 3.3
          - ruby_version: "3.3"
            rails_version: "7.0"
          - ruby_version: "3.3"
            rails_version: "7.1"
          - ruby_version: "3.3"
            rails_version: "7.2"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Build and test
        run: |
          bundle exec appraisal rails-${{ matrix.rails_version }} bundle
